tasks:
  - name: Install AWS SAM
    command: |
      ARCH=$(uname -m)
      if [ "$ARCH" = "x86_64" ]; then
        curl -Lo /tmp/sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        unzip -q /tmp/sam.zip -d /tmp/sam
        sudo /tmp/sam/install
      elif [ "$ARCH" = "aarch64" ]; then
        pip install aws-sam-cli
      fi
